### ISSUE TITLE
Compile Error: cannot find value `ZSTD_c_targetCBlockSize` in this scope

### ISSUE THREAD

**Issue by msrd0** [gyscos/zstd-rs#359]
When enabling the `bindgen` and `pkg-config` feature, `zstd-safe` 7.2.4 fails to compile on Ubuntu LTS. It works on ArchLinux with zstd 1.5.7.

The existence of the `legacy` feature flag that claims to support zstd <0.8 makes me believe that it should work with zstd 1.5.5 out of the box.

## Reproduce

```
 host  $ podman run --rm -it ubuntu

ubuntu $ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04.4 LTS"

ubuntu $ apt update
[...]

ubuntu $ apt install --no-install-recommends ca-certificates cargo git libclang-dev libzstd-dev pkgconf
[...]
Setting up libzstd-dev:amd64 (1.5.5+dfsg2-2build1.1) ...
[...]

ubuntu $ git clone https://github.com/gyscos/zstd-rs
[...]

ubuntu $ cd zstd-rs

ubuntu $ cargo -V
cargo 1.75.0

ubuntu $ cargo build -p zstd-safe --features bindgen,pkg-config
   Compiling zstd-safe v7.2.4 (/root/zstd-rs/zstd-safe)
   Compiling zstd-sys v2.0.16+zstd.1.5.7 (/root/zstd-rs/zstd-safe/zstd-sys)
error[E0425]: cannot find value `ZSTD_c_targetCBlockSize` in this scope
    --> zstd-safe/src/lib.rs:690:18
     |
690  |                 (ZSTD_c_targetCBlockSize, value as c_int)
     |                  ^^^^^^^^^^^^^^^^^^^^^^^ help: a tuple variant with a similar name exists: `TargetCBlockSize`
...
2186 |     TargetCBlockSize(u32),
     |     --------------------- similarly named tuple variant `TargetCBlockSize` defined here

For more information about this error, try `rustc --explain E0425`.
error: could not compile `zstd-safe` (lib) due to previous error
```

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The `legacy` feature is intended to allow decompressing data that was compressed with very old zstd versions (which would otherwise not be readable by a modern decompressor). It is not meant to support building against an old version of the library.

`ZSTD_c_targetCBlockSize` was introduced in zstd 1.5.6, which means that 1.5.5 version you have is just a bit too old. 

Supporting dynamic linking against old version of zstd is not currently planned. You might need to use the vendored version of zstd, or use an older version of the binding. For example, zstd-sys 2.0.9 was working with zstd 1.5.5. zstd-safe 7.0.0 was compatible with it, and the zstd crate 0.13.0 was compatible with that.
